//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testBooks2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string price { get; set; }
        public string status { get; set; }
        public string booking_num { get; set; }
    }
}
